// Code generated by ogen, DO NOT EDIT.
package api

type CreateItemRes interface {
	createItemRes()
}

type DeleteItemRes interface {
	deleteItemRes()
}

type GetBoardRes interface {
	getBoardRes()
}

type GetItemRes interface {
	getItemRes()
}

type RenameToSlugRes interface {
	renameToSlugRes()
}

type ReorderLaneRes interface {
	reorderLaneRes()
}

type RetitleItemRes interface {
	retitleItemRes()
}

type SaveContentRes interface {
	saveContentRes()
}

type SearchItemsRes interface {
	searchItemsRes()
}

type TransitionItemRes interface {
	transitionItemRes()
}
